// <auto-generated />
namespace SaphirCongesCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NoOfDaysFix3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoOfDaysFix3));
        
        string IMigrationMetadata.Id
        {
            get { return "201801221022006_NoOfDaysFix3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
